.PHONY: graphs
graphs:
	cat accounts/accounts_repay.dot | dot -Tsvg -o accounts/repay.dot.svg
	cat accounts/accounts_stake.dot | dot -Tsvg -o accounts/stake.dot.svg
	cat accounts/accounts_borrow.dot | dot -Tsvg -o accounts/borrow.dot.svg
	cat accounts/accounts_init_vault.dot | dot -Tsvg -o accounts/init_vault.dot.svg
	cat accounts/accounts_init_debt_type.dot | dot -Tsvg -o accounts/init_debt_type.dot.svg
	cat accounts/accounts_init_vault_type.dot | dot -Tsvg -o accounts/init_vault_type.dot.svg
	cat accounts/accounts_unstake.dot | dot -Tsvg -o accounts/unstake.dot.svg
